### ISSUE TITLE
Not available in composer, not registered in packagist.org

### ISSUE THREAD

**Issue by josenobile** [faustbrian/CloudFlare-PHP-Client#2]
Hello, 

 - The requested package faustbrian/cloudflare-php-client could not be found in any version, there may be a typo in the package name.

**Comment by faustbrian** [comment]
WIP, not meant to be used in production yet.

**Comment by josenobile** [comment]
Hello, 

I realized

object(BrianFaust\Http\HttpResponse)#7 (1) {
  ["response":"BrianFaust\Http\HttpResponse":private]=>
  object(GuzzleHttp\Psr7\Response)#41 (6) {
    ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
    string(11) "Bad Request"
    ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
    int(400)

Do you know any PHP library to interact with Cloudflare V4 API and include dns_records/import api call?

**Comment by faustbrian** [comment]
Just send a normal HTTP Request through Guzzle with the required Headers, pretty simple.
